name: bydoxe_chart
summary: A Flutter Charts library which paint candle chart, depth chart in Exchange Application.
description: A Flutter Charts library which paint candle chart(support select multi secondary state), depth chart in Exchange Application.
version: 1.0.3
homepage: https://github.com/bydoxe/bydoxe_chart

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
